### ISSUE TITLE
Indicate Progress for "Request a computer analysis"

### ISSUE THREAD

**Issue by LSeelig** [lichess-org/mobile#563] opened 2024-02-20 02:18 UTC
It is not immediately clear that a request has been received by the server. The button grays out, and it almost seems like something has gone wrong for a relatively long time before the analysis graph appears. 

Even then, the graph is filled in in seemingly random segments, and it isn't immediately clear that it isn't done.

Please add a loading animation and, once the analysis graph starts gradually filling, please add some progress indicator to show it isn't complete.

**Comment by veloce** [comment] 2024-02-20 12:30
Duplicate of #532.

**Closed by veloce** 2024-02-20 12:30 UTC
