### ISSUE TITLE
Practice against computer and choose any UCI Chess Engine installed on my device 

### ISSUE THREAD

**Issue by noobCODER912** [lichess-org/mobile#1268] opened 2024-12-17 07:06 UTC
The website has a practice against computer option. I think that should also be included in the apk version. Also, there should be an option to select a chess engine installed on our device and set its parameters manually in both analysis and practice against computer mode.

**Comment by Boubou78000** [comment] 2024-12-17 07:15
Duplicate of #1172

**Comment by tom-anders** [comment] 2024-12-17 10:14
> Duplicate of #1172

Not the second request though (the one about using a custom chess engine). But I doubt that requested feature is in scope of this project (how does that even work on mobile, how would you install another engine and then use it via UCI...?)

**Closed by tom-anders** 2024-12-17 10:14 UTC

**Comment by noobCODER912** [comment] 2024-12-17 14:15
> > Duplicate of #1172
> 
> Not the second request though (the one about using a custom chess engine). But I doubt that requested feature is in scope of this project (how does that even work on mobile, how would you install another engine and then use it via UCI...?) 

We can download apk files of other chess engine ( like LeelaChess0), install them and than run it using a chess app that supports UCI . Just for example this app:- https://play.google.com/store/apps/details?id=com.google.android.chess.  I use this app , but it lacks analysis feature. So , I thought bringing this feature in Lichess would be great.

**Comment by tom-anders** [comment] 2024-12-17 14:19
> > > Duplicate of #1172
> > 
> > 
> > Not the second request though (the one about using a custom chess engine). But I doubt that requested feature is in scope of this project (how does that even work on mobile, how would you install another engine and then use it via UCI...?)
> 
> We can download apk files of other chess engine ( like LeelaChess0), install them and than run it using a chess app that supports UCI . Just for example this app:- https://play.google.com/store/apps/details?id=com.google.android.chess. I use this app , but it lacks analysis feature. So , I thought bringing this feature in Lichess would be great.

Huh, interesting, I did not know something like this is possible. @veloce is this something we might consider as a feature at some point in the future?

**Comment by veloce** [comment] 2024-12-17 15:29
Yes it would be interesting. But that wouldn't work on iOS, right?

**Comment by noobCODER912** [comment] 2024-12-17 15:41
> Yes it would be interesting. But that wouldn't work on iOS, right?

I am not sure if there is any way to do that is iOS, most probably it won't work
