### ISSUE TITLE
The pieces are missplaced on the board on Xiaomi tablet 

### ISSUE THREAD

**Issue by mappachett** [lichess-org/mobile#651] opened 2024-04-26 17:07 UTC
### What is the problem?

![Screenshot_2024-04-26-18-51-09-251_org lichess mobileV2](https://github.com/lichess-org/mobile/assets/104673284/31ff452f-4043-4b61-b2ac-83da451fd900)

### Steps to reproduce the bug

Open the app
Go to any option like puzzle strike 

### What did you expect to happen?

The pieces should be on their position

### What happened instead?

They are missplaced 

### Device Info

Xiaomi pad 5

### Operating System Version

Android 14

**Comment by veloce** [comment] 2024-04-27 10:52
Can you share your screen specs please? Like resolution, pixel ratio, etc. Maybe that'll help because I can't reproduce this problem.

**Comment by mappachett** [comment] 2024-04-28 06:57
Here are the specs:
Resolution 1600 x 2560 pixels, 16:10 ratio (~274 ppi density)
Source: https://m.gsmarena.com/xiaomi_pad_5-11042.php

Regards

**Comment by veloce** [comment] 2024-04-29 16:49
I can't reproduce with an emulator using same screen settings.

**Comment by veloce** [comment] 2024-04-29 16:54
A real device would be needed here to reproduce and fix that bug. Weird thing about this is that the pieces on top of the board are almost correctly placed, and the more at the bottom they are, the more shifted...

**Comment by veloce** [comment] 2024-04-29 17:37
Closing as duplicate of #375

**Closed by veloce** 2024-04-29 17:37 UTC
Labels: bug, help wanted, Missing reproduction
