### ISSUE TITLE
Android version freezing upon reinstallation

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#301] opened 2023-08-30 10:35 UTC
The Android app freezes upon reinstallation on Android version 13. Not so on iPadOS. I couldn't test on any other devices.

This is fixed by clearing the storage, but not by just clearing the cache. It also occurs if you clear the storage before uninstalling (Which it should as Android 11+ removes all app data upon uninstallation)

It appears to have to do with these lines (from `adb logtcat | grep lichess.mobileV2`) that appear when starting the app after a reinstall:

```08-30 12:10:22.071 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.arm64_v8a.dm': No such file or directory
08-30 12:10:22.071 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.arm64_v8a.dm': No such file or directory
08-30 12:10:22.071 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.de.dm': No such file or directory
08-30 12:10:22.071 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.de.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.en.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.en.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.fr.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.fr.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.ru.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.ru.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.xxhdpi.dm': No such file or directory
08-30 12:10:22.072 26610 26610 W ziparchive: Unable to open '/data/app/~~Aqpv8MW0C1W5evGTIkoiTg==/org.lichess.mobileV2-SWo7z7uJMawvnsepU2REmg==/split_config.xxhdpi.dm': No such file or directory
```

Full logs on uninstall (not relevant but whatever) and launch after reinstall:
https://pastebin.com/d3ftHt4R

**Comment by veloce** [comment] 2023-11-21 09:23
Closing as it seems the issue is gone.

**Closed by veloce** 2023-11-21 09:23 UTC
