### ISSUE TITLE
Analysis engine is breaking for various parts of app after app resumes from background

### ISSUE THREAD

**Issue by ijm8710** [lichess-org/mobile#1277] opened 2024-12-19 15:18 UTC
![image](https://github.com/user-attachments/assets/be3f6a2c-24df-4723-8296-3074cd002350)
![image](https://github.com/user-attachments/assets/a0d77d4b-a1c6-4c8a-94a8-ee119c4160bd)
![image](https://github.com/user-attachments/assets/9434905a-1c4d-4a99-95f8-73e2958dd5e5)
![image](https://github.com/user-attachments/assets/f883644f-9b86-4fd9-b28e-440195bb2005)

Sadly don't have great repro steps but have ran into this on 3 separate occasions in past 12 hours so pretty confident it'll be reproducible eventually.  if you hang in app for a bit, the analysis engine just breaks and suggest the same wrong stuff for every game.

Once this happens, it starts referencing the corrupted analysis not just for broadcast but for your own previous games as well. Same corruption design for the engine too! (B1 and c2 in first two examples and then b4/d4 for other example provided)

0.13.10 iOS
Each example is two fold: broadcast and analysis for own games

**Comment by veloce** [comment] 2024-12-20 07:41
Also duplicate of #1013

**Closed by veloce** 2024-12-20 07:41 UTC

**Comment by ijm8710** [comment] 2024-12-20 19:24
Are you sure it's the same? This one has the same engine analysis for every game in weird spots but moves that are impossible .
The other issue said it would use the engine analysis from a previous game?

I saw those other tickets but they seemed different
