### ISSUE TITLE
Stockfish build error

### ISSUE THREAD

**Issue by ZTL-UwU** [lichess-org/mobile#123] opened 2023-04-27 07:02 UTC
It happened both shortly before and after 47558826082486ca6020722041785b09ff930aec.
Ubuntu 22.10, mobile is android 13.

I've tried deleting ~/.pub-cache and .dart_tool multiple times but it never worked.

[err_log.txt](https://github.com/lichess-org/mobile/files/11340416/err_log.txt)
[flutter doctor -v.txt](https://github.com/lichess-org/mobile/files/11340418/flutter.doctor.-v.txt)

**Comment by veloce** [comment] 2023-04-27 10:36
First you should fix your android toolchain. I see errors in `flutter doctor`.

**Comment by veloce** [comment] 2023-04-28 14:00
I don't use ubuntu myself so don't really know what's going on. The CI who can build the app fine, also run on ubuntu, so that could be indeed missing development tools.

Perhaps the original authors of the stockfish plugin can help you? You can try to post the issue in this repo:
https://github.com/ArjanAswal/Stockfish

**Comment by veloce** [comment] 2023-04-28 14:02
About why it builds iOS files: it's just because stockfish src is inside the `ios` folder.

**Comment by veloce** [comment] 2023-04-28 14:05
Maybe one thing to try: install flutter manually (not using `snapd`).

**Comment by brandonpl8** [comment] 2023-05-02 19:25
Removed snapd installation of flutter and installed flutter manually. Stockfish builds fine now. ( Ubuntu 20.04 )

**Comment by veloce** [comment] 2023-05-03 11:17
Good! Would be nice to write sth about it in the wiki.

Even better would be to understand why it doesn't work with snapd but at least there's workaround.

**Comment by JayPi4c** [comment] 2023-05-03 14:37
I can confirm. Removing the snap installation and following the manual installation does solve the problem.
Also I tried building the stockfish plugin and I experienced the same issue. So I guess it would be right to post this issue on that repository and try to find out what's causing the bug with the snap installation in the first place.

**Comment by JayPi4c** [comment] 2023-05-03 14:44
I took the liberty to update the wiki:
https://github.com/lichess-org/mobile/wiki/Setting-up-the-development-environment

I will also create an issue on the stockfish repository referencing this problem.

**Comment by veloce** [comment] 2023-05-04 02:29
Thanks for updating the wiki! I'm closing the issue since there is a workaround and the issue is not really related to this repo.

**Closed by veloce** 2023-05-04 02:29 UTC
