### ISSUE TITLE
Coordinate training cheat

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1215] opened 2024-12-03 20:51 UTC
### What is the problem?

Coordinate trainer supports the abilty to drag your finger on the board and have many tries per second, and when you did an error, it still can count it like a win...

### Steps to reproduce the bug

1. Go to the coordinates trainer
2. Drag your finger among the board

### App version

0.13.2

### Device Info

android 14

### Additional information

I made easily a score of 28 with this trick

**Comment by tom-anders** [comment] 2024-12-03 21:15
Duplicate of https://github.com/lichess-org/mobile/issues/1017

**Closed by tom-anders** 2024-12-03 21:15 UTC
Labels: bug, duplicate
