### ISSUE TITLE
Puzzle storm’s missed problems can’t be analysed

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1225] opened 2024-12-05 07:44 UTC
I have a high puzzle rating: near 2000.

When I do puzzle storm problems, I can’t analyse my missed problems: if I click show the solution, I would lose 50 rating points, not optimal. So I need to skip them.

**Comment by tom-anders** [comment] 2024-12-14 08:28
Is this possible on the website?

**Comment by Boubou78000** [comment] 2024-12-14 08:30
> Is this possible on the website? 

On the website you can do nonrated puzzles, so yes.

**Comment by EmmetSchuler** [comment] 2024-12-14 10:50
I think this is just an extension of having a rated / unrated toggle for standard puzzles supported in the app.

**Comment by tom-anders** [comment] 2024-12-14 11:00
Also, a duplicate of #733

**Closed** 2024-12-14 11:01 UTC
