### ISSUE TITLE
Shapes stay on the screen after solving puzzle

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#840] opened 2024-07-09 06:22 UTC
### What is the problem?

The new drawing mode is great but I noticed a small issue.

When the user draws any shape on the board and solves the puzzle on the Puzzle screen, the shapes stay on the board.

This can be easily fixed by the double tap but I think it'd be better to somehow fix this. 

### Steps to reproduce the bug

1. Go to the Puzzle screen to solve a puzzle
2. Draw shapes on the board
3. Solve the puzzle correctly so you get a new puzzle
4. The shapes stay on the board

https://github.com/lichess-org/mobile/assets/118524250/abef768d-96d4-44e7-9fa4-55f92fd27d0f

### What did you expect to happen?

When a new puzzle is provided, the shapes get cleared off the board

### What happened instead?

The shapes stayed on the board even when getting a new puzzle

### Device Info

Redmi Note 10 5G

### Operating System Version

MIUI 14 / Android 13

### Additional information

I am not sure if this is a bug or not and it's not annoying, so if it doesn't get fixed, it's not really a problem imo

**Comment by veloce** [comment] 2024-07-11 18:31
Not really a bug. #847 does not really fix it, but now making a move will clear shapes, so I think the problem isn't relevant anymore. That's why I'm closing it.

**Closed by veloce** 2024-07-11 18:31 UTC
Labels: bug
