### ISSUE TITLE
Tournament Section 

### ISSUE THREAD

**Issue by vaibhavsection** [lichess-org/mobile#779] opened 2024-06-14 05:40 UTC
App is now in beta stage so tournament Section must be considerable in Play button.
Old app not support Swiss tournament.
So like web site,
Please all tournaments section in new app.
![Screenshot_2024-06-14-11-08-57-31_dc00545bd3b8828f033a02ac25b2d36d](https://github.com/lichess-org/mobile/assets/131532744/b0e7803c-50b4-4c28-b817-3bbb9253112d)

Its new Section beginning
Please do consider my request.
Or any tentative date for such cool feature?

**Comment by HaonRekcef** [comment] 2024-08-31 09:01
duplicate of #535 can be closed

**Closed** 2024-09-02 05:58 UTC
