### ISSUE TITLE
Engine Lines appear for the wrong side to move

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1184] opened 2024-11-25 11:11 UTC
### What is the problem?

When scrolling quickly through a completed game with local evaluation enabled, oftentimes the engine lines do not match the current side to move. I’ve also noticed that many times it will display the wrong side evaluation first and then correct itself, which looks very visually wrong. As of now I have screenshots, but if needed I can provide a screen recording. It seems to be easily reproducible, at least for me. 
![IMG_0276](https://github.com/user-attachments/assets/52de20f0-2972-43d1-a9c6-558db59d73dc)
![IMG_0275](https://github.com/user-attachments/assets/3c5c3f73-275e-4ae0-a228-39104658179e)

### Steps to reproduce the bug

Go to a previously played game
Enable computer analysis
Flip through the moves at a quicker pace

The engine arrows appear visually glitchy, and at times get stuck on the wrong side to move

### App version

0.13.2

### Device Info

iPhone 13 mini IOS 18

### Additional information

I used 1 core, and 2 engine lines

**Comment by veloce** [comment] 2024-12-04 15:13
Duplicate of #1217

**Closed by veloce** 2024-12-04 15:13 UTC
Labels: bug
