### ISSUE TITLE
Suggest adding the tournaments to the app

### ISSUE THREAD

**Issue by mshahedi83** [lichess-org/mobile#805] opened 2024-06-29 19:35 UTC
Wow, the puzzle with all the options are available in the new app, If the tournaments adds like this, it will be really great.
especially team tournaments, because team tournament links doesn't open with old app and about upcoming tournaments only notification is given but it isn't displayed on the home page next to the other tournaments (in website and old app).
Good luck! Thanks.

**Comment by HaonRekcef** [comment] 2024-08-31 09:01
duplicate of #535 can be closed

**Closed** 2024-09-02 06:07 UTC
