### ISSUE TITLE
Font inconsistency in puzzle score

### ISSUE THREAD

**Issue by altbert** [lichess-org/mobile#1138] opened 2024-11-06 15:55 UTC
![20241106_124543.jpg](https://github.com/user-attachments/assets/d16cb52f-c7ee-45b7-aeb5-aa9ae20634aa)

When a minus one digit score is displayed, the font is larger than the rest of the scores.

Device: Samsung S9
Android: 10
App Version : v0.12.2
Theme: Dark (The bug may also be in the White theme, didn't test)

**Comment by tom-anders** [comment] 2024-11-06 16:33
@veloce duplicate of https://github.com/lichess-org/mobile/issues/1090 I think...?

**Closed** 2024-12-09 11:00 UTC
