### ISSUE TITLE
Engine Suggestions and current Position not in Sync 

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#1217] opened 2024-12-04 12:53 UTC
### What is the problem?

Cached move suggestions are replaced by engine calculations for a position that does not match the current board.

### Steps to reproduce the bug

1. Open an analysis board.  
2. Set the search time to a fixed amount (e.g., 6 seconds).  
3. Allow the engine to calculate in the initial position for more than 6 seconds.  
4. Make a move to change the position.  
5. Return to the initial position.  
6. Observe that the engine is suggesting moves for Black

Video:
https://github.com/user-attachments/assets/c437969d-dc07-4001-a161-8c86dbfa4eed

### App version

0.13.4

### Device Info

-

**Comment by Boubou78000** [comment] 2024-12-04 13:00
Duplicate of #1184

**Comment by veloce** [comment] 2024-12-04 15:14
Keeping this one as it has a better description. Thanks for the report @HaonRekcef , I think it is a regression due to the new search time parameter. Will investigate.

**Closed** 2024-12-07 09:52 UTC
Labels: bug
