### ISSUE TITLE
Animation loading new screens is lagging on iPad

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#399] opened 2023-12-19 08:59 UTC
The animation loading new screens seems to be a bit laggy or has to little frames on my iPad Pro (2017) iPadOS 17.1.2. Like this the user experience is not smooth at all. See attached a video:
https://github.com/lichess-org/mobile/assets/78898963/a97f7f80-76da-42aa-b9c8-38cc75a09b99

**Comment by veloce** [comment] 2023-12-19 09:36
Have you some dev experience? because here just a video is not enough for me to know what is going on and I don't have an iPad Pro to try reproduce something.
So it would be nice to have real figures for a start, launch the app in profile mode and check the frame rate.

**Comment by HaonRekcef** [comment] 2023-12-19 09:51
I do have some small experience however none with flutter. Also I do not have a mac so I think I can not test my own build on the iPad. I can however test the different Version in test flight and the behaviour seems to be introduced in the 0.6.1 version and was fine in the 0.5.11 Version . If you know how to better test different versions without a mac, I would be happy to help determine when the issue was introduced.

**Comment by veloce** [comment] 2023-12-20 23:19
I see. That could be an issue with Impeller engine. This engine was designed by flutter to overcome some performance issues, and it is supposed to work well. But on some screens I also noticed lags when scrolling.
I hope the flutter team will eventually fix these issues.

**Comment by kneuner** [comment] 2024-01-05 02:07
I noticed a lot of issues on iOS on 0.6.1 with lag and stuttering throughout. But it has been improved/fixed in 0.6.9. I don't know if the cause of this bug was positively identified, but it seems to not be an issue now.

**Comment by veloce** [comment] 2024-01-05 12:37
Closing it then.

**Closed by veloce** 2024-01-05 12:37 UTC
Labels: cat: performance
