### ISSUE TITLE
Play vs stockfish

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1304] opened 2024-12-24 10:17 UTC
Add a play vs stockfish (online) button.
You can already play vs stockfish (online) by clicking on the rematch button of a game you played with it.

Design preview:
![Screenshot_20241224_110842.jpg](https://github.com/user-attachments/assets/7f2a5aad-19eb-44ef-b857-2427a3512e31)

**Comment by tom-anders** [comment] 2024-12-24 10:23
Duplicate of #745, please check for existing issues before creating a new one

**Closed by tom-anders** 2024-12-24 10:23 UTC
